esphome:
  name: bksocket
  friendly_name: BKSocket

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:
  baud_rate: 0
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BK S 00 fallback"
    password: !secret fallback_pw

captive_portal:
    

# Status BLUE led on PIN 8, inverted
status_led:
  pin: 
    number: P8
    inverted: True

# Relay on PIN 6
switch:
  - platform: gpio
    name: Relay 1
    id: rel_1
    pin: P6
    restore_mode: ALWAYS_ON
    icon: "mdi:power"
    on_turn_on: 
      then: 
        - switch.turn_on: pwr_led
    on_turn_off: 
      then:
        - switch.turn_off: pwr_led


# Pwr GREEN led on PIN 9, inverted
  - platform: gpio
    id: pwr_led
    name: PWR LED
    pin: P9
    inverted: True

script:
  - id: blink_script
    then:
      - switch.toggle: pwr_led
      - delay: 500ms
      - switch.toggle: pwr_led
      - delay: 500ms          
      - switch.toggle: pwr_led
      - delay: 500ms
      - switch.toggle: pwr_led
      - delay: 500ms          
      - switch.toggle: pwr_led
      - delay: 500ms
      - switch.toggle: pwr_led
      - delay: 500ms     
      - switch.toggle: pwr_led
      - delay: 500ms
      - switch.toggle: pwr_led
      - delay: 500ms     
      - switch.toggle: pwr_led
      - delay: 500ms
      - switch.toggle: pwr_led
      - delay: 500ms     
      - switch.toggle: pwr_led
      - delay: 500ms
      - switch.toggle: pwr_led
      - delay: 500ms     
      - switch.toggle: pwr_led
      - delay: 500ms
      - switch.toggle: pwr_led
      - delay: 500ms     
      - switch.toggle: pwr_led
      - delay: 500ms
      - switch.toggle: pwr_led
      - delay: 500ms     
      - switch.toggle: pwr_led
      - delay: 500ms
      - switch.toggle: pwr_led
      - delay: 500ms   
      - switch.toggle: pwr_led
      - delay: 500ms
      - switch.toggle: pwr_led
      - delay: 500ms     
  
binary_sensor:
  - platform: gpio
    name: Power Button
    id: pwr_button
    pin: 
      number: P7
      inverted: True
    on_click: 
      then:
        - switch.toggle: rel_1

        

button:
  - platform: template
    
    name: Power Cyclr Load
    id: pwr_cyc_button
    
    # Optional variables:
    icon: "mdi:restart"
    on_press:
      - logger.log: "Button pressed"
      - switch.turn_off: rel_1
      - delay: 10s
      - switch.turn_on: rel_1
          

  - platform: template
    name: Identify Device
    id: ident_device
    icon: "mdi:led-on"
    on_press: 
      then:
        
        - script.execute: blink_script

# UART on TX1 / RX1 (check pin numbers below!)
uart:
  
  tx_pin: 11  # Replace with correct TX1 pin number
  rx_pin: 10  # Replace with correct RX1 pin number
  stop_bits: 1
  baud_rate: 9600

sensor:
  - platform: bl0942
    
    voltage:
      name: "BL0942 Voltage"
    current:
      name: "BL0942 Current"
    power:
      name: "BL0942 Power"
    energy:
      name: "BL0942 Energy"
    update_interval: 10s
    voltage_reference: 32000    # DPS 21
    current_reference: 124180   # DPS 22 * 10
    power_reference: 309.1      # DPS 23 / 10
    energy_reference: 2653      # DPS 24
